matrix:
    include:
        - language: java
          jdk:
            - oraclejdk8
          services:
            - docker
          before-install:
            - chmod +x gradlew
            - chmod +x gradle/wrapper/gradle-wrapper.jar
          script:
            - ./gradlew test build
          after_success:
            - bash <(curl -s https://codecov.io)
        - language: node_js
          node_js:
              - "8"
          addons:
              apt:
                  sources:
                      - google-chrome
                  packages:
                      - google-chrome-stable
          cache:
              directories:
                  - ./frontend/node_modules
          install:
              - cd frontend && npm install && cd ..
          script:
              - cd frontend && npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI && cd ..
